### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by NN---** [CrazyPandaLimited/panda-lib#1]
Consider using if constexpr instead of regular if when the expression is compile time such as is_same.

Consider using unordered_map instead of map.
The order mostly is not important as the fast lookup.

**Comment by SmorkalovG** [comment]
Thanks for feedback.
If I understand right, ir is about cast.h and dyn_cast cache. Yes, the improvement is good.
This code is old and originally even older than  C++11 and there was no hash for type_info. unordered_map should be better, I will benchmark it.
Not sure about if constexpr. It requires C++17 and current minimum version is 14. It can be solved with macro but it is not so important now.

**Comment by GSmorkalov** [comment]
We checked. Map is faster for this case. Maybe another unordered_map implementation is faster but std one is not. Thank you!
